import { defineConfig, globalIgnores } from 'eslint/config';

import { nextJsConfig } from '@ordre/config/eslint/next';

export default defineConfig([
  // Generated by fumadocs / fumadocs-openapi - not ours to lint.
  globalIgnores(['.source/**', 'content/api-docs/**']),
  {
    extends: [...nextJsConfig],
  },
  {
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
]);
