/**
 * Auth schema (HAND-OWNED).
 *
 * The auth *tables* (user, session, account, verification) are generated by the
 * Better Auth CLI into `./better-auth.ts` - that file is a build artifact and
 * must never be hand-edited (run `pnpm --filter api auth:generate` to refresh
 * it). The generator also emits Drizzle `relations()` there, but we deliberately
 * do NOT route those to the Drizzle client.
 *
 * Instead, this file owns the auth `relations()`. Owning them here lets us add
 * cross-table relations the generator can't know about (e.g. `user -> workspaces`)
 * without losing them on the next regenerate. The barrel (`./index.ts`) exports
 * the tables from `better-auth.ts` and the relations from here, so the client
 * only ever sees this file's relations.
 *
 * Rule of thumb: tables come from `better-auth.ts`; everything auth/user-domain
 * we maintain ourselves lives here.
 *
 * The generator has no switches for two fixes we need on its timestamp columns
 * (making them timezone-aware, and giving `updated_at` a default), so
 * `auth:generate` pipes its output through `scripts/patch-better-auth-schema.ts`,
 * which applies them and fails the command if it cannot. Names are left exactly
 * as generated. Nothing here is maintained by hand - adjust that script instead.
 */
import { relations } from 'drizzle-orm';

import { account, session, user } from './better-auth.ts';

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));
